services:
  app:
    build: .
    container_name: tyradex-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_NEO4J_URI=${NEO4J_URI}
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=${NEO4J_USER}
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=${NEO4J_PASSWORD}
      - SERVER_SERVLET_CONTEXT_PATH=/v3