spring.application.name=Tyradex
spring.neo4j.uri=neo4j://127.0.0.1:7687
spring.neo4j.authentication.username=tyradex
spring.neo4j.authentication.password=tyradex_auth_api
spring.data.neo4j.database=neo4j
logging.level.org.springframework.data.neo4j=DEBUG
logging.level.org.neo4j.driver=DEBUG